server:
  port: 8080
  mode: debug

database:
  path: ./data/music.db

webdav:
  url: http://192.168.1.3:9000
  username: music
  password: music
  root_path: /dav

scan:
  extensions:
    - .mp3
  batch_size: 50
  concurrent: 5